### ISSUE TITLE
MVP Frame 작성

### ISSUE THREAD

**Issue by aeri123443** [onezero-dju/2024-UCD_WEB_FRONT#1]
# 👥Squad
> Frontend

## ✏️ Description
- Web Server와의 연동을 위한 기초 틀 마련

## ✅ To-do
- [x] Sidebar 마크업
- [x] Login Page 마크업
- [x] Meeting Page 마크업
- [x] 로그인 기능
- [x] Selected ID 상태관리
- [x] Organigation, Channel, Category, Meeting ID 기반 Elements 표시
- [x] 각 컴포넌트 Stories 생성
 
## ⏰ Expected time
- ~24.08.11

## ➕ Etc
- 기타 기입 사항 (코멘트, 자료 등)
