### ISSUE TITLE
로그인 및 회원가입 API 통신 구현

### ISSUE THREAD

**Issue by Jinviz** [onezero-dju/2024-UCD_WEB_FRONT#10]
# 👥Squad
> Web Frontend

## ✏️ Description
- 해당 기능에 대해 간결히 설명

## ✅ To-do
- [x] 로그인 Post API 
- [x] 회원가입 Post API
- [x] react-cookie로 토큰 전역 관리
- [x] 토큰 없을 때 루트로 리다이렉션하는 훅
- [x] 로그아웃 구현
 
## ⏰ Expected time
- ~24.10.02

**Comment by Jinviz** [comment]
서버와 정상 통신 및 로그인 테스트 완료
