### ISSUE TITLE
MVP API 연결

### ISSUE THREAD

**Issue by aeri123443** [onezero-dju/2024-UCD_WEB_FRONT#4]
# 👥Squad
> Web Frontend

## ✏️ Description
- MVP API 연결 및 테스트 

## ✅ To-do
- [x] 회원: 회원가입, 로그인, 회원정보 
- [ ] 조직: 조직 생성, 사용자가 속한 조직 정보 조회 
- [ ] 채널: 채널 생성, 채널 정보 조회
- [x] 통합: 회원정보, 조직정보, 채널정보
- [ ] (백엔드 협업 필요) API 직접 연결 
 
## ⏰ Expected time
- ~24.09.08 (백엔드와 일정 조율 필요)

## ➕ Etc
- API 플랫폼으로 개발 후 백엔드와 협업하여 직접 연결 필요
