### ISSUE TITLE
로그인 후 메인 진입 로직

### ISSUE THREAD

**Issue by Jinviz** [onezero-dju/2024-UCD_WEB_FRONT#8]
# 👥Squad
> Web Frontend

## ✏️ Description
- 조직 여부 판단하여 메인 페이지 진입

## ✅ To-do
- [x] 조직 여부 검증 로직 구현 
- [x] 조직X: (모달창) 조직 생성 또는 조직 신청
- [x] 조직O: 메인 페이지 진입
 
## ⏰ Expected time
- ~24.10.05
